title: "Sébastien Doussang | dev"
description: "Mon portfolio et blog"
url: "https://doussangsebastien.github.io"
author: "Sébastien Doussang"
lang: "en"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# index
birthdate: 2006-08-29

# blog
paginate: 5
paginate_path: "/blog/page:num/"
